// <auto-generated />
using System;
using GSM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706155725_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GSM.Domain.Models.DailyBalance", b =>
                {
                    b.Property<int>("DailyBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyBalanceId"));

                    b.Property<DateOnly>("BalanceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ClosingVolumeActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosingVolumeCalculated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LossLiters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDispatched")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalReceived")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DailyBalanceId");

                    b.HasIndex("TankId");

                    b.ToTable("DailyBalances");
                });

            modelBuilder.Entity("GSM.Domain.Models.Dispatch", b =>
                {
                    b.Property<int>("DispatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispatchId"));

                    b.Property<TimeOnly>("CreatedAt")
                        .HasColumnType("time");

                    b.Property<DateOnly>("DispatchDate")
                        .HasColumnType("date");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientOrg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<string>("TruckNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("VolumeInvoiceLiters")
                        .HasColumnType("float");

                    b.Property<string>("WaybillNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DispatchId");

                    b.HasIndex("TankId");

                    b.HasIndex("UserId");

                    b.ToTable("Dispatches");
                });

            modelBuilder.Entity("GSM.Domain.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<double>("Density")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GSM.Domain.Models.Tank", b =>
                {
                    b.Property<int>("TankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TankId"));

                    b.Property<double>("CapacityLiters")
                        .HasColumnType("float");

                    b.Property<double>("CurentVolumeLiters")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("TankNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TankId");

                    b.HasIndex("ProductId");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("GSM.Domain.Models.TankMeasurement", b =>
                {
                    b.Property<int>("TankMeasurementsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TankMeasurementsId"));

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("VolumeLiters")
                        .HasColumnType("float");

                    b.HasKey("TankMeasurementsId");

                    b.HasIndex("TankId");

                    b.HasIndex("UserId");

                    b.ToTable("TankMeasurements");
                });

            modelBuilder.Entity("GSM.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GSM.Domain.Models.WagonReceipt", b =>
                {
                    b.Property<int>("WagonReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WagonReceiptId"));

                    b.Property<TimeOnly>("CreatedAt")
                        .HasColumnType("time");

                    b.Property<double>("DiscrepancyLiters")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("VolumeActualLiters")
                        .HasColumnType("float");

                    b.Property<double>("VolumeInvoiceLiters")
                        .HasColumnType("float");

                    b.Property<string>("WagonNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaybillNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WagonReceiptId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TankId");

                    b.HasIndex("UserId");

                    b.ToTable("WagonReceipts");
                });

            modelBuilder.Entity("GSM.Domain.Models.DailyBalance", b =>
                {
                    b.HasOne("GSM.Domain.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("GSM.Domain.Models.Dispatch", b =>
                {
                    b.HasOne("GSM.Domain.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSM.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GSM.Domain.Models.Tank", b =>
                {
                    b.HasOne("GSM.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GSM.Domain.Models.TankMeasurement", b =>
                {
                    b.HasOne("GSM.Domain.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSM.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GSM.Domain.Models.WagonReceipt", b =>
                {
                    b.HasOne("GSM.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GSM.Domain.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSM.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tank");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
